services:
  chinadns-ng:
    image: yahuiwong/chinadns-ng:latest
    build:
       context: .
       dockerfile: Dockerfile
       platforms:
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm"
       args:
        REF: 2024.10.14
    container_name: chinadns-ng
    restart: unless-stopped
    privileged: true
    # command: 
    #   - 
    # cap_add:
    #  - NET_ADMIN
    #  - NET_BIND_SERVICE
    #  - NET_RAW
    # network_mode: host
#    networks:
#      dockervlan:
#        ipv4_address: 192.168.2.2 # container (gateway) ip address
    # environment:
    #   VNC_ENABLED: 1
    ports:
      - "443:443"
    #   - "6080:6080"
    # volumes:
      # - './chinadns-ng/config.json:/etc/chinadns-ng/config.json'

#networks:
#  dockervlan:
#    name: dockervlan
#    driver: macvlan
#    driver_opts:
#      parent: eth0 # modify it to match your network interface name
#    ipam:
#      config: # modify the following content to match your network env
#        - subnet: "192.168.2.0/24"
#          ip_range: "192.168.2.64/26"
#          gateway: "192.168.2.1"

# if you already have a macvlan
# networks:
#   yourvlan:
#     external: true